command! Bashrc :e ~/.local/share/nvim/site/pack/packer/start/user_env_manager_notes_exercises/bash_modules
command! Bookmarks :e ~/.local/share/nvim/site/pack/packer/start/user_env_manager_notes_exercises/bookmarks.txt
command! Commands :e ~/.local/share/nvim/site/pack/packer/start/user_env_manager_notes_exercises/plugin/commands.vim
command! Exercises :e ~/.local/share/nvim/site/pack/packer/start/user_env_manager_notes_exercises/exercises
command! Ftplugins :e ~/.local/share/nvim/site/pack/packer/start/user_env_manager_notes_exercises/ftplugin/
command! Plugins :e ~/.local/share/nvim/site/pack/packer/start/user_env_manager_notes_exercises/plugin/
command! Ftplugin :e ~/.vim/ftplugin
command! Notes :e ~/.local/share/nvim/site/pack/packer/start/user_env_manager_notes_exercises/notes/
command! Schedule :e ~/.local/share/nvim/site/pack/packer/start/user_env_manager_notes_exercises/schedule.txt
command! ScriptingHelp :h usr_41.txt
command! Todos :e ~/.local/share/nvim/site/pack/packer/start/user_env_manager_notes_exercises/todos.txt
command! Vimpacks :e ~/.vim/pack/
command! Vimrc :e ~/.vimrc
