command Bashrc :e ~/.vim/pack/01-user_env_manager_notes_exercises/start/user_env_manager_notes_exercises/bash_modules
command Bookmarks :e ~/.vim/pack/01-user_env_manager_notes_exercises/start/user_env_manager_notes_exercises/bookmarks.txt
command Commands :e ~/.vim/pack/01-user_env_manager_notes_exercises/start/user_env_manager_notes_exercises/plugin/commands.vim
command Exercises :e ~/.vim/pack/01-user_env_manager_notes_exercises/start/user_env_manager_notes_exercises/exercises
command Ftplugin :e ~/.vim/ftplugin
command Notes :e ~/.vim/pack/01-user_env_manager_notes_exercises/start/user_env_manager_notes_exercises/notes/
command Schedule :e ~/.vim/pack/01-user_env_manager_notes_exercises/start/user_env_manager_notes_exercises/schedule.txt
command ScriptingHelp :h usr_41.txt
command Todos :e ~/.vim/pack/01-user_env_manager_notes_exercises/start/user_env_manager_notes_exercises/todos.txt
command Vimpacks :e ~/.vim/pack/
command Vimrc :e ~/.vimrc
