command Bashrc :e /Users/andrewmiller/.local/share/nvim/site/pack/packer/start/user_env_manager_notes_exercises/bash_modules
command Bookmarks :e /Users/andrewmiller/.local/share/nvim/site/pack/packer/start/user_env_manager_notes_exercises/bookmarks.txt
command Commands :e /Users/andrewmiller/.local/share/nvim/site/pack/packer/start/user_env_manager_notes_exercises/plugin/commands.vim
command Exercises :e /Users/andrewmiller/.local/share/nvim/site/pack/packer/start/user_env_manager_notes_exercises/exercises
command Ftplugins :e /Users/andrewmiller/.local/share/nvim/site/pack/packer/start/user_env_manager_notes_exercises/ftplugin/
command Plugins :e /Users/andrewmiller/.local/share/nvim/site/pack/packer/start/user_env_manager_notes_exercises/plugin/
command Ftplugin :e ~/.vim/ftplugin
command Notes :e /Users/andrewmiller/.local/share/nvim/site/pack/packer/start/user_env_manager_notes_exercises/notes/
command Schedule :e /Users/andrewmiller/.local/share/nvim/site/pack/packer/start/user_env_manager_notes_exercises/schedule.txt
command ScriptingHelp :h usr_41.txt
command Todos :e /Users/andrewmiller/.local/share/nvim/site/pack/packer/start/user_env_manager_notes_exercises/todos.txt
command Vimpacks :e ~/.vim/pack/
command Vimrc :e ~/.vimrc
